language:
  - java 

jdk:
  - openjdk

env:
  global:
    - DITAOT="3.7"
    - URL="https://github.com/dita-ot/dita-ot/releases/download/$DITAOT/dita-ot-$DITAOT.zip"

before_script:
  - zip -qr org.doctales.reveal.zip . -x *.zip* *.git/* *temp/* *out/*
  - curl -LO $URL
  - unzip -q dita-ot-$DITAOT.zip
  - chmod +x dita-ot-$DITAOT/bin/dita
  - chmod +x dita-ot-$DITAOT/bin/ant
  - dita-ot-$DITAOT/bin/dita --install org.doctales.reveal.zip
  - BASEDIR=$(dirname "$0")

script:
  - dita-ot-$DITAOT/bin/dita -i samples/doctales.ditamap -f reveal -v -Dargs.reveal.css="plugins/org.doctales.reveal/css/doctales.css" -Dargs.reveal.theme="doctales"

notifications:
  slack:
    rooms:
      - doctales:BkI4k7awSFS5X5aT04Y3vHQ9#reveal
